# Verwenden des offiziellen Python-Images als Basis
FROM python:3

# Arbeitsverzeichnis im Container setzen
WORKDIR /app

# Kopieren des aktuellen Verzeichnisses in das Arbeitsverzeichnis im Container
COPY . /app

# Installieren von Abhängigkeiten
RUN pip install -r requirements.txt

# Befehl zum Ausführen der Anwendung
CMD ["python", "webserver.py"]
